name: default

on:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./Build.ps1
        shell: pwsh

      - name: Test
        run: ./Test.ps1
        shell: pwsh

      - name: Publish
        run: ./Publish.ps1
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
