name: default

on:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo "Hello, World!"
